# Generated by Django 4.1.7 on 2023-03-25 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book_author', to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genre', to='books.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='theme',
            field=models.ManyToManyField(related_name='book_theme', to='books.theme'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,4}$')]),
        ),
    ]
