name: DRF_tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3.3.0

        - name: Setup Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4.5.0

          with:
              python-version: "3.10"

        - name: Setup Poetry
          uses: Gr1N/setup-poetry@v8

        - name: Install requirements
          run: |
              poetry install
              poetry export -f requirements.txt --output requirements.txt
              pip install -r requirements.txt

        - name: Run Flake8
          run: |
              pflake8 .

        - name: Run tests
          run: |
              cd book
              python manage.py test
